import type { ClothingItem } from '@/types';

export const initialItems: ClothingItem[] = [
  {
    id: '1',
    title: 'Men\'s Classic Kurta',
    description: 'Elegant silk kurta for festive occasions. Traditional embroidery with a modern cut.',
    price: 79.99,
    discount: 15,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '2',
    title: 'Women\'s Anarkali Suit',
    description: 'Beautiful georgette Anarkali suit with intricate gota patti work. Perfect for weddings.',
    price: 129.99,
    discount: 0,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens anarkali',
  },
  {
    id: '3',
    title: 'Kids Sherwani Set',
    description: 'Cute and comfortable sherwani set for boys. Ideal for cultural events.',
    price: 49.99,
    discount: 10,
    size: '2-4Y, 4-6Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids sherwani',
  },
  {
    id: '4',
    title: 'Ethnic Embroidered Saree',
    description: 'Luxurious Banarasi silk saree with all-over embroidery. Comes with a matching blouse piece.',
    price: 199.99,
    discount: 20,
    size: 'Free Size',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic saree',
  },
  {
    id: '5',
    title: 'Western Denim Jacket',
    description: 'Stylish blue denim jacket with a distressed look. Versatile for casual outings.',
    price: 65.00,
    discount: 0,
    size: 'S, M, L, XL',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'denim jacket',
  },
  {
    id: '6',
    title: 'Men\'s Casual Shirt',
    description: 'Comfortable cotton shirt for everyday wear. Available in multiple colors.',
    price: 35.50,
    discount: 0,
    size: 'S, M, L, XL, XXL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens shirt',
  },
  {
    id: '7',
    title: 'Women\'s Floral Maxi Dress',
    description: 'Light and airy floral maxi dress, perfect for summer. Features an elastic waistband.',
    price: 55.99,
    discount: 5,
    size: 'XS, S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens dress',
  },
  {
    id: '8',
    title: 'Kids Printed T-Shirt',
    description: 'Soft cotton t-shirt with fun prints for kids. Durable and easy to wash.',
    price: 15.00,
    discount: 0,
    size: '1-2Y, 2-3Y, 3-4Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids tshirt',
  },
  // Added items start here
  {
    id: '9',
    title: 'Elegant Men\'s Sherwani',
    description: 'A beautifully crafted sherwani for weddings and formal events.',
    price: 189.99,
    discount: 10,
    size: 'L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens sherwani',
  },
  {
    id: '10',
    title: 'Vibrant Women\'s Lehenga',
    description: 'A stunning lehenga choli with heavy embroidery, perfect for bridal wear.',
    price: 299.99,
    discount: 0,
    size: 'S, M',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens lehenga',
  },
  {
    id: '11',
    title: 'Cute Kids\' Ethnic Gown',
    description: 'A comfortable and stylish ethnic gown for little girls.',
    price: 39.99,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids gown',
  },
  {
    id: '12',
    title: 'Handwoven Ethnic Shawl',
    description: 'A warm and intricate handwoven shawl with traditional patterns.',
    price: 85.00,
    discount: 0,
    size: 'Free Size',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic shawl',
  },
  {
    id: '13',
    title: 'Modern Western Jumpsuit',
    description: 'A chic and comfortable jumpsuit for a modern, stylish look.',
    price: 75.00,
    discount: 25,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western jumpsuit',
  },
  {
    id: '14',
    title: 'Classic Men\'s Trousers',
    description: 'Well-fitted formal trousers for a professional look.',
    price: 45.00,
    discount: 0,
    size: '32, 34, 36',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens trousers',
  },
  {
    id: '15',
    title: 'Stylish Women\'s Kurti',
    description: 'A trendy kurti with unique prints, suitable for casual and office wear.',
    price: 40.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens kurti',
  },
  {
    id: '16',
    title: 'Comfy Kids\' Pajama Set',
    description: 'A soft cotton pajama set to ensure a good night\'s sleep for your child.',
    price: 25.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids pajama',
  },
  {
    id: '17',
    title: 'Designer Ethnic Clutch',
    description: 'An exquisitely designed clutch to complement your ethnic attire.',
    price: 50.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic clutch',
  },
  {
    id: '18',
    title: 'Casual Western Top',
    description: 'A simple yet elegant top for daily wear.',
    price: 30.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western top',
  },
  {
    id: '19',
    title: 'Men\'s Silk Scarf',
    description: 'A luxurious silk scarf to add a touch of class to your outfit.',
    price: 35.00,
    discount: 0,
    size: 'Free Size',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens scarf',
  },
  {
    id: '20',
    title: 'Women\'s Georgette Saree',
    description: 'A light and flowy georgette saree, perfect for daytime events.',
    price: 95.00,
    discount: 10,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens saree',
  },
  {
    id: '21',
    title: 'Kids\' Denim Dungarees',
    description: 'Fun and durable denim dungarees for playful kids.',
    price: 45.00,
    discount: 0,
    size: '2-4Y, 4-6Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids dungarees',
  },
  {
    id: '22',
    title: 'Ethnic Jhumka Earrings',
    description: 'Traditional jhumka earrings to complete your ethnic look.',
    price: 25.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic earrings',
  },
  {
    id: '23',
    title: 'Western Pencil Skirt',
    description: 'A formal pencil skirt for a sharp, professional appearance.',
    price: 55.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western skirt',
  },
  {
    id: '24',
    title: 'Men\'s Pathani Suit',
    description: 'A traditional Pathani suit that offers both comfort and style.',
    price: 110.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens suit',
  },
  {
    id: '25',
    title: 'Women\'s Palazzo Pants',
    description: 'Comfortable and wide-legged palazzo pants for a relaxed style.',
    price: 35.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens pants',
  },
  {
    id: '26',
    title: 'Kids\' Party Frock',
    description: 'A beautiful frock for birthday parties and special occasions.',
    price: 60.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids frock',
  },
  {
    id: '27',
    title: 'Ethnic Mojari Shoes',
    description: 'Handcrafted mojari shoes to go with your traditional wear.',
    price: 70.00,
    discount: 0,
    size: '8, 9, 10',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic shoes',
  },
  {
    id: '28',
    title: 'Western Leather Belt',
    description: 'A high-quality leather belt to accessorize your outfits.',
    price: 40.00,
    discount: 0,
    size: '32-38',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western belt',
  },
  {
    id: '29',
    title: 'Men\'s Waistcoat',
    description: 'A stylish waistcoat to wear over a kurta or shirt.',
    price: 65.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens waistcoat',
  },
  {
    id: '30',
    title: 'Women\'s Crop Top',
    description: 'A trendy crop top that can be paired with skirts or jeans.',
    price: 28.00,
    discount: 0,
    size: 'S, M',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens top',
  },
  {
    id: '31',
    title: 'Kids\' Hooded Sweatshirt',
    description: 'A warm and cozy sweatshirt for kids during colder months.',
    price: 35.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids sweatshirt',
  },
  {
    id: '32',
    title: 'Ethnic Potli Bag',
    description: 'A traditional potli bag with beadwork, perfect for festivities.',
    price: 45.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic bag',
  },
  {
    id: '33',
    title: 'Western Trench Coat',
    description: 'A classic trench coat for a sophisticated winter look.',
    price: 150.00,
    discount: 0,
    size: 'M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western coat',
  },
  {
    id: '34',
    title: 'Men\'s Bandhgala Jacket',
    description: 'A royal Bandhgala jacket for formal occasions.',
    price: 170.00,
    discount: 0,
    size: 'L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens jacket',
  },
  {
    id: '35',
    title: 'Women\'s Sharara Suit',
    description: 'A fashionable sharara suit with flared pants and a short kameez.',
    price: 140.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens suit',
  },
  {
    id: '36',
    title: 'Kids\' Traditional Dhoti Kurta',
    description: 'A cute dhoti kurta set for boys for cultural functions.',
    price: 55.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids dhoti',
  },
  {
    id: '37',
    title: 'Ethnic Maang Tikka',
    description: 'A beautiful piece of head jewelry to adorn your forehead.',
    price: 30.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic jewelry',
  },
  {
    id: '38',
    title: 'Western High-Waist Jeans',
    description: 'Flattering high-waist jeans for a trendy, casual look.',
    price: 60.00,
    discount: 0,
    size: '28, 30, 32',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western jeans',
  },
  {
    id: '39',
    title: 'Men\'s Brocade Kurta',
    description: 'A rich brocade kurta for a touch of opulence.',
    price: 120.00,
    discount: 0,
    size: 'M, L',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '40',
    title: 'Women\'s Chiffon Dupatta',
    description: 'A light and elegant chiffon dupatta with a delicate border.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens dupatta',
  },
  {
    id: '41',
    title: 'Kids\' Lehenga Choli',
    description: 'A miniature lehenga choli for girls to wear at festivals.',
    price: 75.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids lehenga',
  },
  {
    id: '42',
    title: 'Ethnic Nose Ring (Nath)',
    description: 'A traditional nose ring to complete a bridal look.',
    price: 35.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic nath',
  },
  {
    id: '43',
    title: 'Western Cardigan',
    description: 'A soft knit cardigan, perfect for layering.',
    price: 50.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western cardigan',
  },
  {
    id: '44',
    title: 'Men\'s Formal Shoes',
    description: 'Polished leather shoes for a complete formal attire.',
    price: 80.00,
    discount: 0,
    size: '8, 9, 10',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens shoes',
  },
  {
    id: '45',
    title: 'Women\'s Patiala Salwar',
    description: 'A comfortable and voluminous Patiala salwar.',
    price: 45.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens salwar',
  },
  {
    id: '46',
    title: 'Kids\' Kurta Pajama',
    description: 'A simple and elegant kurta pajama set for boys.',
    price: 50.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids kurta',
  },
  {
    id: '47',
    title: 'Ethnic Bangles Set',
    description: 'A colorful set of bangles to match your outfits.',
    price: 20.00,
    discount: 0,
    size: '2.4, 2.6, 2.8',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic bangles',
  },
  {
    id: '48',
    title: 'Western Scarf',
    description: 'A stylish scarf to accessorize your western outfits.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western scarf',
  },
  {
    id: '49',
    title: 'Men\'s Nehru Jacket',
    description: 'A sleeveless Nehru jacket, a modern take on traditional wear.',
    price: 75.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens jacket',
  },
  {
    id: '50',
    title: 'Women\'s Designer Blouse',
    description: 'A beautifully designed blouse to pair with sarees or lehengas.',
    price: 60.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens blouse',
  },
  {
    id: '51',
    title: 'Kids\' Sports Shorts',
    description: 'Comfortable shorts for sports and outdoor activities.',
    price: 20.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids shorts',
  },
  {
    id: '52',
    title: 'Ethnic Kamarbandh',
    description: 'A decorative waistband to accentuate your ethnic look.',
    price: 40.00,
    discount: 0,
    size: 'Adjustable',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic kamarbandh',
  },
  {
    id: '53',
    title: 'Western Beanie Cap',
    description: 'A warm beanie cap for the winter season.',
    price: 20.00,
    discount: 0,
    size: 'One Size',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western cap',
  },
  {
    id: '54',
    title: 'Men\'s Cotton Lungi',
    description: 'A traditional and comfortable cotton lungi for daily use.',
    price: 20.00,
    discount: 0,
    size: 'Free Size',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens lungi',
  },
  {
    id: '55',
    title: 'Women\'s Kaftan Dress',
    description: 'A loose and airy kaftan dress for maximum comfort.',
    price: 65.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens kaftan',
  },
  {
    id: '56',
    title: 'Kids\' Raincoat',
    description: 'A waterproof raincoat to keep your child dry during monsoons.',
    price: 30.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids raincoat',
  },
  {
    id: '57',
    title: 'Ethnic Turban (Pagdi)',
    description: 'A pre-stitched turban for weddings and special occasions.',
    price: 50.00,
    discount: 0,
    size: 'Standard',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic turban',
  },
  {
    id: '58',
    title: 'Western Sunglasses',
    description: 'Stylish sunglasses to protect your eyes from the sun.',
    price: 35.00,
    discount: 0,
    size: 'One Size',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western sunglasses',
  },
  {
    id: '59',
    title: 'Men\'s Jodhpuri Suit',
    description: 'A regal Jodhpuri suit for a majestic look.',
    price: 220.00,
    discount: 0,
    size: 'L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens jodhpuri',
  },
  {
    id: '60',
    title: 'Women\'s A-Line Skirt',
    description: 'A flattering A-line skirt for a feminine silhouette.',
    price: 48.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens skirt',
  },
  {
    id: '61',
    title: 'Kids\' Woolen Sweater',
    description: 'A warm woolen sweater to keep your child cozy.',
    price: 40.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids sweater',
  },
  {
    id: '62',
    title: 'Ethnic Anklets (Payal)',
    description: 'A pair of beautiful silver-plated anklets.',
    price: 30.00,
    discount: 0,
    size: 'Standard',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic anklets',
  },
  {
    id: '63',
    title: 'Western Bodycon Dress',
    description: 'A figure-hugging bodycon dress for parties.',
    price: 70.00,
    discount: 0,
    size: 'XS, S, M',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western dress',
  },
  {
    id: '64',
    title: 'Men\'s Dhoti Pants',
    description: 'Modern dhoti pants that combine tradition with trend.',
    price: 55.00,
    discount: 0,
    size: 'Free Size',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens dhoti',
  },
  {
    id: '65',
    title: 'Women\'s Tunic Top',
    description: 'A versatile tunic top that can be worn with leggings or jeans.',
    price: 42.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens tunic',
  },
  {
    id: '66',
    title: 'Kids\' Winter Jacket',
    description: 'A padded winter jacket for ultimate warmth.',
    price: 65.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids jacket',
  },
  {
    id: '67',
    title: 'Ethnic Brooch',
    description: 'An elegant brooch to accessorize a saree or sherwani.',
    price: 25.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic brooch',
  },
  {
    id: '68',
    title: 'Western Leggings',
    description: 'Stretchable and comfortable leggings for everyday wear.',
    price: 22.00,
    discount: 0,
    size: 'S, M, L, XL',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western leggings',
  },
  {
    id: '69',
    title: 'Men\'s Kurta with Jacket',
    description: 'A stylish kurta set that comes with a contrasting jacket.',
    price: 135.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '70',
    title: 'Women\'s Jumpsuit Saree',
    description: 'A modern and innovative jumpsuit saree for the fashion-forward woman.',
    price: 160.00,
    discount: 0,
    size: 'S, M',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens jumpsuit',
  },
  {
    id: '71',
    title: 'Kids\' Cartoon-Print Shirt',
    description: 'A fun shirt with cartoon prints that kids will love.',
    price: 28.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids shirt',
  },
  {
    id: '72',
    title: 'Ethnic Hand-Painted Dupatta',
    description: 'A unique hand-painted dupatta that is a piece of art.',
    price: 75.00,
    discount: 0,
    size: 'Free Size',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic dupatta',
  },
  {
    id: '73',
    title: 'Western Pleated Skirt',
    description: 'A classic pleated skirt for a timeless look.',
    price: 52.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western skirt',
  },
  {
    id: '74',
    title: 'Men\'s Traditional Turban',
    description: 'A majestic turban for a royal groom look.',
    price: 85.00,
    discount: 0,
    size: 'Standard',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens turban',
  },
  {
    id: '75',
    title: 'Women\'s Long Skirt',
    description: 'A flowy long skirt with ethnic prints.',
    price: 68.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens skirt',
  },
  {
    id: '76',
    title: 'Kids\' Onesie',
    description: 'A cute and comfortable onesie for infants.',
    price: 32.00,
    discount: 0,
    size: '0-6M, 6-12M',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids onesie',
  },
  {
    id: '77',
    title: 'Ethnic Necklace Set',
    description: 'A complete necklace set with matching earrings.',
    price: 90.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic necklace',
  },
  {
    id: '78',
    title: 'Western Blazer Dress',
    description: 'A chic blazer dress for a powerful and stylish statement.',
    price: 88.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western dress',
  },
  {
    id: '79',
    title: 'Men\'s Chikankari Kurta',
    description: 'An elegant kurta with fine Chikankari embroidery from Lucknow.',
    price: 145.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '80',
    title: 'Women\'s Cape Top',
    description: 'A stylish top with an attached cape for a dramatic flair.',
    price: 58.00,
    discount: 0,
    size: 'S, M',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens top',
  },
  {
    id: '81',
    title: 'Kids\' Romper Suit',
    description: 'An adorable romper suit for babies, easy to wear.',
    price: 35.00,
    discount: 0,
    size: '6-12M, 12-18M',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids romper',
  },
  {
    id: '82',
    title: 'Ethnic Hair Accessories',
    description: 'A set of traditional hair accessories for braids and buns.',
    price: 28.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic hair',
  },
  {
    id: '83',
    title: 'Western Boyfriend Jeans',
    description: 'Relaxed fit boyfriend jeans for ultimate comfort and style.',
    price: 62.00,
    discount: 0,
    size: '28, 30, 32',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western jeans',
  },
  {
    id: '84',
    title: 'Men\'s Angrakha Kurta',
    description: 'A traditional Angrakha style kurta with a side-tie design.',
    price: 98.00,
    discount: 0,
    size: 'L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '85',
    title: 'Women\'s Dhoti Saree',
    description: 'A pre-draped dhoti saree for a hassle-free, modern ethnic look.',
    price: 175.00,
    discount: 0,
    size: 'Free Size',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens saree',
  },
  {
    id: '86',
    title: 'Kids\' Denim Skirt',
    description: 'A cute and versatile denim skirt for little girls.',
    price: 38.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids skirt',
  },
  {
    id: '87',
    title: 'Ethnic Bindi Pack',
    description: 'A pack of decorative bindis in various shapes and colors.',
    price: 10.00,
    discount: 0,
    size: 'N/A',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic bindi',
  },
  {
    id: '88',
    title: 'Western Peplum Top',
    description: 'A top with a flared peplum waist for a flattering shape.',
    price: 48.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western top',
  },
  {
    id: '89',
    title: 'Men\'s Linen Shirt',
    description: 'A breathable linen shirt, perfect for summer days.',
    price: 55.00,
    discount: 0,
    size: 'M, L, XL, XXL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens shirt',
  },
  {
    id: '90',
    title: 'Women\'s Asymmetric Kurta',
    description: 'A kurta with a modern, asymmetric hemline.',
    price: 62.00,
    discount: 0,
    size: 'M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens kurta',
  },
  {
    id: '91',
    title: 'Kids\' Tutu Dress',
    description: 'A fluffy tutu dress for the little ballerina in your life.',
    price: 55.00,
    discount: 0,
    size: '3-5Y, 5-7Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids dress',
  },
  {
    id: '92',
    title: 'Ethnic Bridal Veil (Dupatta)',
    description: 'A heavily embellished veil to complete a bridal lehenga.',
    price: 110.00,
    discount: 0,
    size: 'Free Size',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic veil',
  },
  {
    id: '93',
    title: 'Western Off-Shoulder Top',
    description: 'A trendy off-shoulder top for a chic look.',
    price: 40.00,
    discount: 0,
    size: 'S, M, L',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western top',
  },
  {
    id: '94',
    title: 'Men\'s Khadi Jacket',
    description: 'A jacket made from handspun khadi fabric.',
    price: 85.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens jacket',
  },
  {
    id: '95',
    title: 'Women\'s Pant Saree',
    description: 'A modern fusion of pants and saree, easy to wear and stylish.',
    price: 155.00,
    discount: 0,
    size: 'S, M',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens saree',
  },
  {
    id: '96',
    title: 'Kids\' Capris',
    description: 'Comfortable capri pants for kids for everyday play.',
    price: 25.00,
    discount: 0,
    size: '4-6Y, 6-8Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids capris',
  },
  {
    id: '97',
    title: 'Ethnic Toe Rings',
    description: 'A pair of adjustable silver-plated toe rings.',
    price: 15.00,
    discount: 0,
    size: 'Adjustable',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic rings',
  },
  {
    id: '98',
    title: 'Western Shirt Dress',
    description: 'A comfortable and stylish dress designed like a long shirt.',
    price: 68.00,
    discount: 0,
    size: 'M, L, XL',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'western dress',
  },
  {
    id: '99',
    title: 'Men\'s Printed T-shirt',
    description: 'A casual t-shirt with cool, modern prints.',
    price: 25.00,
    discount: 0,
    size: 'S, M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens tshirt',
  },
  {
    id: '100',
    title: 'Women\'s Cold-Shoulder Top',
    description: 'A top with cut-outs at the shoulders for a trendy look.',
    price: 42.00,
    discount: 50,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens top',
  },
];
