import type { ClothingItem } from '@/types';

export const initialItems: ClothingItem[] = [
  {
    id: '1',
    title: 'Men\'s Classic Kurta',
    description: 'Elegant silk kurta for festive occasions. Traditional embroidery with a modern cut.',
    price: 79.99,
    size: 'M, L, XL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens kurta',
  },
  {
    id: '2',
    title: 'Women\'s Anarkali Suit',
    description: 'Beautiful georgette Anarkali suit with intricate gota patti work. Perfect for weddings.',
    price: 129.99,
    size: 'S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens anarkali',
  },
  {
    id: '3',
    title: 'Kids Sherwani Set',
    description: 'Cute and comfortable sherwani set for boys. Ideal for cultural events.',
    price: 49.99,
    size: '2-4Y, 4-6Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids sherwani',
  },
  {
    id: '4',
    title: 'Ethnic Embroidered Saree',
    description: 'Luxurious Banarasi silk saree with all-over embroidery. Comes with a matching blouse piece.',
    price: 199.99,
    size: 'Free Size',
    category: 'Ethnic',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'ethnic saree',
  },
  {
    id: '5',
    title: 'Western Denim Jacket',
    description: 'Stylish blue denim jacket with a distressed look. Versatile for casual outings.',
    price: 65.00,
    size: 'S, M, L, XL',
    category: 'Western',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'denim jacket',
  },
  {
    id: '6',
    title: 'Men\'s Casual Shirt',
    description: 'Comfortable cotton shirt for everyday wear. Available in multiple colors.',
    price: 35.50,
    size: 'S, M, L, XL, XXL',
    category: 'Men',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'mens shirt',
  },
  {
    id: '7',
    title: 'Women\'s Floral Maxi Dress',
    description: 'Light and airy floral maxi dress, perfect for summer. Features an elastic waistband.',
    price: 55.99,
    size: 'XS, S, M, L',
    category: 'Women',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'womens dress',
  },
  {
    id: '8',
    title: 'Kids Printed T-Shirt',
    description: 'Soft cotton t-shirt with fun prints for kids. Durable and easy to wash.',
    price: 15.00,
    size: '1-2Y, 2-3Y, 3-4Y',
    category: 'Kids',
    imageUrl: 'https://placehold.co/600x800.png',
    imageHint: 'kids tshirt',
  },
];
