
import type { ClothingItem } from '@/types';

// Helper to assign adminId cyclically
const getAdminId = (index: number) => `admin${(index % 5) + 1}`;

export const initialItems: Omit<ClothingItem, 'finalPrice' | 'searchableText'>[] = [
  {
    id: '1',
    title: 'Men\'s Classic Kurta',
    adminId: getAdminId(0),
    description: 'Elegant silk kurta for festive occasions. Traditional embroidery with a modern cut.',
    price: 79.99,
    discount: 15,
    size: 'M, L, XL',
    colors: 'White, Beige, Black',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens kurta white'],
    specifications: [
      'Fabric: Blended Silk',
      'Fit: Regular',
      'Sleeve: Full Sleeves',
      'Care: Dry Clean Only'
    ],
  },
  {
    id: '2',
    title: 'Women\'s Anarkali Suit',
    adminId: getAdminId(1),
    description: 'Beautiful georgette Anarkali suit with intricate gota patti work. Perfect for weddings.',
    price: 129.99,
    discount: 0,
    size: 'S, M, L',
    colors: 'Pink, Blue, Yellow',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens anarkali pink'],
    specifications: [
      'Fabric: Georgette',
      'Work: Gota Patti',
      'Occasion: Wedding, Festive'
    ],
  },
  {
    id: '3',
    title: 'Kids Sherwani Set',
    adminId: getAdminId(2),
    description: 'Cute and comfortable sherwani set for boys. Ideal for cultural events.',
    price: 49.99,
    discount: 10,
    size: 'M, L',
    colors: 'Gold, Red, Blue',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids sherwani gold'],
    specifications: ['Fabric: Cotton Silk', 'Includes: Sherwani, Pajama'],
  },
  {
    id: '4',
    title: 'Ethnic Embroidered Saree',
    adminId: getAdminId(3),
    description: 'Luxurious Banarasi silk saree with all-over embroidery. Comes with a matching blouse piece.',
    price: 199.99,
    discount: 20,
    size: 'Free Size',
    colors: 'Red, Green, Navy',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic saree red'],
    specifications: [
      'Fabric: Banarasi Silk',
      'Length: 5.5 meters',
      'Includes matching blouse piece'
    ],
  },
  {
    id: '5',
    title: 'Western Denim Jacket',
    adminId: getAdminId(4),
    description: 'Stylish blue denim jacket with a distressed look. Versatile for casual outings.',
    price: 65.00,
    discount: 0,
    size: 'S, M, L, XL',
    colors: 'Blue, Black, Gray',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['denim jacket blue'],
    specifications: ['Fabric: 100% Cotton Denim', 'Fit: Regular'],
  },
  {
    id: '6',
    title: 'Men\'s Casual Shirt',
    adminId: getAdminId(5),
    description: 'Comfortable cotton shirt for everyday wear. Available in multiple colors.',
    price: 35.50,
    discount: 0,
    size: 'S, M, L, XL, XXL',
    colors: 'White, Black, Blue, Pink',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens shirt white'],
    specifications: ['Fabric: 100% Cotton', 'Fit: Slim Fit'],
  },
  {
    id: '7',
    title: 'Women\'s Floral Maxi Dress',
    adminId: getAdminId(6),
    description: 'Light and airy floral maxi dress, perfect for summer. Features an elastic waistband.',
    price: 55.99,
    discount: 5,
    size: 'XS, S, M, L',
    colors: 'Red, Yellow, Blue',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens dress floral'],
    specifications: ['Fabric: Rayon', 'Length: Ankle-length'],
  },
  {
    id: '8',
    title: 'Kids Printed T-Shirt',
    adminId: getAdminId(7),
    description: 'Soft cotton t-shirt with fun prints for kids. Durable and easy to wash.',
    price: 15.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Gray, White, Red',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids tshirt grey'],
    specifications: ['Fabric: 100% Cotton', 'Neck: Round Neck'],
  },
  {
    id: '9',
    title: 'Elegant Men\'s Sherwani',
    adminId: getAdminId(8),
    description: 'A beautifully crafted sherwani for weddings and formal events.',
    price: 189.99,
    discount: 10,
    size: 'L, XL',
    colors: 'Beige, Gold, Navy',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens sherwani beige'],
    specifications: ['Fabric: Jacquard', 'Work: Zari Embroidery'],
  },
  {
    id: '10',
    title: 'Vibrant Women\'s Lehenga',
    adminId: getAdminId(9),
    description: 'A stunning lehenga choli with heavy embroidery, perfect for bridal wear.',
    price: 299.99,
    discount: 0,
    size: 'S, M',
    colors: 'Red, Maroon, Pink',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens lehenga red'],
    specifications: ['Fabric: Velvet', 'Work: Sequins and Zari'],
  },
  {
    id: '11',
    title: 'Cute Kids\' Ethnic Gown',
    adminId: getAdminId(10),
    description: 'A comfortable and stylish ethnic gown for little girls.',
    price: 39.99,
    discount: 0,
    size: 'M, L',
    colors: 'Pink, Purple, Blue',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids gown pink'],
    specifications: ['Fabric: Net and Satin', 'Occasion: Party Wear'],
  },
  {
    id: '12',
    title: 'Handwoven Ethnic Shawl',
    adminId: getAdminId(11),
    description: 'A warm and intricate handwoven shawl with traditional patterns.',
    price: 85.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Brown, Black, Red',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic shawl brown'],
    specifications: ['Fabric: Wool Blend', 'Craft: Handwoven'],
  },
  {
    id: '13',
    title: 'Modern Western Jumpsuit',
    adminId: getAdminId(12),
    description: 'A chic and comfortable jumpsuit for a modern, stylish look.',
    price: 75.00,
    discount: 25,
    size: 'S, M, L',
    colors: 'White, Black, Navy',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western jumpsuit white'],
    specifications: ['Fabric: Crepe', 'Fit: Relaxed'],
  },
  {
    id: '14',
    title: 'Classic Men\'s Trousers',
    adminId: getAdminId(13),
    description: 'Well-fitted formal trousers for a professional look.',
    price: 45.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Gray, Black, Brown',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens trousers gray'],
    specifications: ['Fabric: Cotton Blend', 'Fit: Slim Straight'],
  },
  {
    id: '15',
    title: 'Stylish Women\'s Kurti',
    adminId: getAdminId(14),
    description: 'A trendy kurti with unique prints, suitable for casual and office wear.',
    price: 40.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Yellow, Blue, Green',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens kurti yellow'],
    specifications: ['Fabric: Cotton', 'Length: Knee-Length'],
  },
  {
    id: '16',
    title: 'Comfy Kids\' Pajama Set',
    adminId: getAdminId(15),
    description: 'A soft cotton pajama set to ensure a good night\'s sleep for your child.',
    price: 25.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Pink, Yellow',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids pajama set blue'],
    specifications: ['Fabric: 100% Cotton Jersey', 'Includes: Top and Bottom'],
  },
  {
    id: '17',
    title: 'Designer Ethnic Clutch',
    adminId: getAdminId(16),
    description: 'An exquisitely designed clutch to complement your ethnic attire.',
    price: 50.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Silver, Red',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic clutch gold'],
    specifications: ['Material: Silk with Beadwork', 'Closure: Clasp'],
  },
  {
    id: '18',
    title: 'Casual Western Top',
    adminId: getAdminId(17),
    description: 'A simple yet elegant top for daily wear.',
    price: 30.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'White, Black, Beige',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western top white'],
    specifications: ['Fabric: Viscose', 'Fit: Regular'],
  },
  {
    id: '19',
    title: 'Men\'s Silk Scarf',
    adminId: getAdminId(18),
    description: 'A luxurious silk scarf to add a touch of class to your outfit.',
    price: 35.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Black, Navy, Gray',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens scarf black'],
    specifications: ['Fabric: 100% Silk', 'Dimensions: 180cm x 30cm'],
  },
  {
    id: '20',
    title: 'Women\'s Georgette Saree',
    adminId: getAdminId(19),
    description: 'A light and flowy georgette saree, perfect for daytime events.',
    price: 95.00,
    discount: 10,
    size: 'Free Size',
    colors: 'Pink, Peach, Mint Green',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens saree pink'],
    specifications: ['Fabric: Georgette', 'Work: Digital Print'],
  },
  {
    id: '21',
    title: 'Kids\' Denim Dungarees',
    adminId: getAdminId(20),
    description: 'Fun and durable denim dungarees for playful kids.',
    price: 45.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Light Blue',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids dungarees blue'],
    specifications: ['Fabric: Denim', 'Straps: Adjustable'],
  },
  {
    id: '22',
    title: 'Ethnic Jhumka Earrings',
    adminId: getAdminId(21),
    description: 'Traditional jhumka earrings to complete your ethnic look.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic earrings gold'],
    specifications: ['Material: Alloy', 'Plating: Gold-plated'],
  },
  {
    id: '23',
    title: 'Western Pencil Skirt',
    adminId: getAdminId(22),
    description: 'A formal pencil skirt for a sharp, professional appearance.',
    price: 55.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Black, Gray, Navy',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western skirt black'],
    specifications: ['Fabric: Polyester Blend', 'Length: Knee-length'],
  },
  {
    id: '24',
    title: 'Men\'s Pathani Suit',
    adminId: getAdminId(23),
    description: 'A traditional Pathani suit that offers both comfort and style.',
    price: 110.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Black, White, Blue',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens pathani suit black'],
    specifications: ['Fabric: Cotton', 'Style: Pathani'],
  },
  {
    id: '25',
    title: 'Women\'s Palazzo Pants',
    adminId: getAdminId(24),
    description: 'Comfortable and wide-legged palazzo pants for a relaxed style.',
    price: 35.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Black, White, Beige',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens palazzo pants black'],
    specifications: ['Fabric: Rayon', 'Waist: Elasticated'],
  },
  {
    id: '26',
    title: 'Kids\' Party Frock',
    adminId: getAdminId(25),
    description: 'A beautiful frock for birthday parties and special occasions.',
    price: 60.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Pink, White, Gold',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids party frock pink'],
    specifications: ['Fabric: Tulle and Satin', 'Lining: Cotton'],
  },
  {
    id: '27',
    title: 'Ethnic Mojari Shoes',
    adminId: getAdminId(26),
    description: 'Handcrafted mojari shoes to go with your traditional wear.',
    price: 70.00,
    discount: 0,
    size: 'L, XL',
    colors: 'Brown, Black, Tan',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic mojari brown'],
    specifications: ['Material: Leather', 'Embroidery: Threadwork'],
  },
  {
    id: '28',
    title: 'Western Leather Belt',
    adminId: getAdminId(27),
    description: 'A high-quality leather belt to accessorize your outfits.',
    price: 40.00,
    discount: 0,
    size: 'M, L',
    colors: 'Brown, Black',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western belt brown'],
    specifications: ['Material: Genuine Leather', 'Buckle: Metal'],
  },
  {
    id: '29',
    title: 'Men\'s Waistcoat',
    adminId: getAdminId(28),
    description: 'A stylish waistcoat to wear over a kurta or shirt.',
    price: 65.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Blue, Black, Gray',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens waistcoat blue'],
    specifications: ['Fabric: Blended', 'Style: Nehru Jacket'],
  },
  {
    id: '30',
    title: 'Women\'s Crop Top',
    adminId: getAdminId(29),
    description: 'A trendy crop top that can be paired with skirts or jeans.',
    price: 28.00,
    discount: 0,
    size: 'S, M',
    colors: 'Black, White, Red',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens crop top black'],
    specifications: ['Fabric: Cotton Lycra', 'Sleeves: Half'],
  },
  {
    id: '31',
    title: 'Kids\' Hooded Sweatshirt',
    adminId: getAdminId(30),
    description: 'A warm and cozy sweatshirt for kids during colder months.',
    price: 35.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Gray, Black, Blue',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids sweatshirt gray'],
    specifications: ['Fabric: Fleece', 'Pockets: Kangaroo Pocket'],
  },
  {
    id: '32',
    title: 'Ethnic Potli Bag',
    adminId: getAdminId(31),
    description: 'A traditional potli bag with beadwork, perfect for festivities.',
    price: 45.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Red, Gold, Green',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic potli bag red'],
    specifications: ['Fabric: Silk', 'Drawstring closure'],
  },
  {
    id: '33',
    title: 'Western Trench Coat',
    adminId: getAdminId(32),
    description: 'A classic trench coat for a sophisticated winter look.',
    price: 150.00,
    discount: 0,
    size: 'M, L',
    colors: 'Beige, Black, Navy',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western trench coat beige'],
    specifications: ['Fabric: Cotton Gabardine', 'Double-breasted'],
  },
  {
    id: '34',
    title: 'Men\'s Bandhgala Jacket',
    adminId: getAdminId(33),
    description: 'A royal Bandhgala jacket for formal occasions.',
    price: 170.00,
    discount: 0,
    size: 'L, XL',
    colors: 'Black, Navy, Maroon',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens bandhgala jacket black'],
    specifications: ['Fabric: Terry Rayon', 'Fit: Slim'],
  },
  {
    id: '35',
    title: 'Women\'s Sharara Suit',
    adminId: getAdminId(34),
    description: 'A fashionable sharara suit with flared pants and a short kameez.',
    price: 140.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Green, Yellow, Pink',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens sharara suit green'],
    specifications: ['Fabric: Georgette', 'Work: Mirror Work'],
  },
  {
    id: '36',
    title: 'Kids\' Traditional Dhoti Kurta',
    adminId: getAdminId(35),
    description: 'A cute dhoti kurta set for boys for cultural functions.',
    price: 55.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Yellow, Orange, White',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids dhoti kurta yellow'],
    specifications: ['Fabric: Cotton Silk', 'Includes: Kurta and Dhoti'],
  },
  {
    id: '37',
    title: 'Ethnic Maang Tikka',
    adminId: getAdminId(36),
    description: 'A beautiful piece of head jewelry to adorn your forehead.',
    price: 30.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Pearl',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic maang tikka gold'],
    specifications: ['Material: Alloy', 'Stones: Kundan'],
  },
  {
    id: '38',
    title: 'Western High-Waist Jeans',
    adminId: getAdminId(37),
    description: 'Flattering high-waist jeans for a trendy, casual look.',
    price: 60.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Black, Light Blue',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western jeans blue'],
    specifications: ['Fabric: Denim with Stretch', 'Style: Skinny Fit'],
  },
  {
    id: '39',
    title: 'Men\'s Brocade Kurta',
    adminId: getAdminId(38),
    description: 'A rich brocade kurta for a touch of opulence.',
    price: 120.00,
    discount: 0,
    size: 'M, L',
    colors: 'Gold, Black, Maroon',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens kurta gold brocade'],
    specifications: ['Fabric: Brocade', 'Fit: Regular'],
  },
  {
    id: '40',
    title: 'Women\'s Chiffon Dupatta',
    adminId: getAdminId(39),
    description: 'A light and elegant chiffon dupatta with a delicate border.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Pink, Blue, White, Red',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens dupatta pink'],
    specifications: ['Fabric: Chiffon', 'Length: 2.25 meters'],
  },
  {
    id: '41',
    title: 'Kids\' Lehenga Choli',
    adminId: getAdminId(40),
    description: 'A miniature lehenga choli for girls to wear at festivals.',
    price: 75.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Pink, Green',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids lehenga choli blue'],
    specifications: ['Fabric: Silk Blend', 'Includes: Skirt, Top, Dupatta'],
  },
  {
    id: '42',
    title: 'Ethnic Nose Ring (Nath)',
    adminId: getAdminId(41),
    description: 'A traditional nose ring to complete a bridal look.',
    price: 35.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic nose ring gold'],
    specifications: ['Material: Brass', 'Style: Clip-on'],
  },
  {
    id: '43',
    title: 'Western Cardigan',
    adminId: getAdminId(42),
    description: 'A soft knit cardigan, perfect for layering.',
    price: 50.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Gray, Beige, Black',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western cardigan gray'],
    specifications: ['Fabric: Acrylic Wool', 'Sleeves: Long'],
  },
  {
    id: '44',
    title: 'Men\'s Formal Shoes',
    adminId: getAdminId(43),
    description: 'Polished leather shoes for a complete formal attire.',
    price: 80.00,
    discount: 0,
    size: 'L, XL, XXL',
    colors: 'Black, Brown',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens formal shoes black'],
    specifications: ['Material: Faux Leather', 'Sole: TPR'],
  },
  {
    id: '45',
    title: 'Women\'s Patiala Salwar',
    adminId: getAdminId(44),
    description: 'A comfortable and voluminous Patiala salwar.',
    price: 45.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Black, Red, Blue, White',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens patiala salwar black'],
    specifications: ['Fabric: Cotton', 'Style: Patiala'],
  },
  {
    id: '46',
    title: 'Kids\' Kurta Pajama',
    adminId: getAdminId(45),
    description: 'A simple and elegant kurta pajama set for boys.',
    price: 50.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'White, Blue, Yellow',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids kurta pajama white'],
    specifications: ['Fabric: Cotton', 'Set of 2'],
  },
  {
    id: '47',
    title: 'Ethnic Bangles Set',
    adminId: getAdminId(46),
    description: 'A colorful set of bangles to match your outfits.',
    price: 20.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Multicolor',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic bangles multicolor'],
    specifications: ['Material: Metal and Silk Thread', 'Set of 24'],
  },
  {
    id: '48',
    title: 'Western Scarf',
    adminId: getAdminId(47),
    description: 'A stylish scarf to accessorize your western outfits.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Plaid, Black, Gray',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western scarf plaid'],
    specifications: ['Fabric: Viscose', 'Pattern: Plaid'],
  },
  {
    id: '49',
    title: 'Men\'s Nehru Jacket',
    adminId: getAdminId(48),
    description: 'A sleeveless Nehru jacket, a modern take on traditional wear.',
    price: 75.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Black, Blue, Brown',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens nehru jacket black'],
    specifications: ['Fabric: Linen Blend', 'Sleeveless'],
  },
  {
    id: '50',
    title: 'Women\'s Designer Blouse',
    adminId: getAdminId(49),
    description: 'A beautifully designed blouse to pair with sarees or lehengas.',
    price: 60.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Red, Gold, Black',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens designer blouse red'],
    specifications: ['Fabric: Raw Silk', 'Back: Dori Tie-up'],
  },
  {
    id: '51',
    title: 'Kids\' Sports Shorts',
    adminId: getAdminId(50),
    description: 'Comfortable shorts for sports and outdoor activities.',
    price: 20.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Red, Blue, Black',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids sports shorts red'],
    specifications: ['Fabric: Polyester', 'Fit: Athletic'],
  },
  {
    id: '52',
    title: 'Ethnic Kamarbandh',
    adminId: getAdminId(51),
    description: 'A decorative waistband to accentuate your ethnic look.',
    price: 40.00,
    discount: 0,
    size: 'Adjustable',
    colors: 'Gold, Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic kamarbandh gold'],
    specifications: ['Material: Metal Alloy', 'Plating: Gold'],
  },
  {
    id: '53',
    title: 'Western Beanie Cap',
    adminId: getAdminId(52),
    description: 'A warm beanie cap for the winter season.',
    price: 20.00,
    discount: 0,
    size: 'One Size',
    colors: 'Gray, Black, Red',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western beanie gray'],
    specifications: ['Fabric: Acrylic Knit', 'Style: Slouchy'],
  },
  {
    id: '54',
    title: 'Men\'s Cotton Lungi',
    adminId: getAdminId(53),
    description: 'A traditional and comfortable cotton lungi for daily use.',
    price: 20.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Blue, Green, Red',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens lungi blue checked'],
    specifications: ['Fabric: 100% Cotton', 'Pattern: Checked'],
  },
  {
    id: '55',
    title: 'Women\'s Kaftan Dress',
    adminId: getAdminId(54),
    description: 'A loose and airy kaftan dress for maximum comfort.',
    price: 65.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Printed, Black, White',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens kaftan dress printed'],
    specifications: ['Fabric: Viscose Rayon', 'Style: Kaftan'],
  },
  {
    id: '56',
    title: 'Kids\' Raincoat',
    adminId: getAdminId(55),
    description: 'A waterproof raincoat to keep your child dry during monsoons.',
    price: 30.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Yellow, Blue, Pink',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids raincoat yellow'],
    specifications: ['Material: PVC', 'Hooded: Yes'],
  },
  {
    id: '57',
    title: 'Ethnic Turban (Pagdi)',
    adminId: getAdminId(56),
    description: 'A pre-stitched turban for weddings and special occasions.',
    price: 50.00,
    discount: 0,
    size: 'Standard',
    colors: 'Red, Pink, Orange',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic turban red'],
    specifications: ['Fabric: Silk', 'Style: Pre-stitched'],
  },
  {
    id: '58',
    title: 'Western Sunglasses',
    adminId: getAdminId(57),
    description: 'Stylish sunglasses to protect your eyes from the sun.',
    price: 35.00,
    discount: 0,
    size: 'One Size',
    colors: 'Black, Brown',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western sunglasses black'],
    specifications: ['Frame Material: Metal', 'Lens: UV Protected'],
  },
  {
    id: '59',
    title: 'Men\'s Jodhpuri Suit',
    adminId: getAdminId(58),
    description: 'A regal Jodhpuri suit for a majestic look.',
    price: 220.00,
    discount: 0,
    size: 'L, XL',
    colors: 'Blue, Black, White',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens jodhpuri suit blue'],
    specifications: ['Fabric: Velvet', 'Includes: Jacket and Trousers'],
  },
  {
    id: '60',
    title: 'Women\'s A-Line Skirt',
    adminId: getAdminId(59),
    description: 'A flattering A-line skirt for a feminine silhouette.',
    price: 48.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Floral, Black, Red',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens a-line skirt floral'],
    specifications: ['Fabric: Cotton', 'Pattern: Floral Print'],
  },
  {
    id: '61',
    title: 'Kids\' Woolen Sweater',
    adminId: getAdminId(60),
    description: 'A warm woolen sweater to keep your child cozy.',
    price: 40.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Gray, Navy, Red',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids woolen sweater gray'],
    specifications: ['Fabric: Wool Blend', 'Sleeves: Full'],
  },
  {
    id: '62',
    title: 'Ethnic Anklets (Payal)',
    adminId: getAdminId(61),
    description: 'A pair of beautiful silver-plated anklets.',
    price: 30.00,
    discount: 0,
    size: 'Standard',
    colors: 'Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic anklets silver'],
    specifications: ['Material: Alloy', 'Plating: Silver'],
  },
  {
    id: '63',
    title: 'Western Bodycon Dress',
    adminId: getAdminId(62),
    description: 'A figure-hugging bodycon dress for parties.',
    price: 70.00,
    discount: 0,
    size: 'XS, S, M',
    colors: 'Black, Red, Blue',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western bodycon dress black'],
    specifications: ['Fabric: Spandex Blend', 'Fit: Bodycon'],
  },
  {
    id: '64',
    title: 'Men\'s Dhoti Pants',
    adminId: getAdminId(63),
    description: 'Modern dhoti pants that combine tradition with trend.',
    price: 55.00,
    discount: 0,
    size: 'Free Size',
    colors: 'White, Beige, Black',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens dhoti pants white'],
    specifications: ['Fabric: Cotton Rayon', 'Waist: Drawstring'],
  },
  {
    id: '65',
    title: 'Women\'s Tunic Top',
    adminId: getAdminId(64),
    description: 'A versatile tunic top that can be worn with leggings or jeans.',
    price: 42.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'White, Blue, Pink',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens tunic top white'],
    specifications: ['Fabric: Cotton Slub', 'Length: Hip-length'],
  },
  {
    id: '66',
    title: 'Kids\' Winter Jacket',
    adminId: getAdminId(65),
    description: 'A padded winter jacket for ultimate warmth.',
    price: 65.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Red, Blue, Black',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids winter jacket red'],
    specifications: ['Material: Polyester', 'Filling: Synthetic'],
  },
  {
    id: '67',
    title: 'Ethnic Brooch',
    adminId: getAdminId(66),
    description: 'An elegant brooch to accessorize a saree or sherwani.',
    price: 25.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic brooch gold'],
    specifications: ['Material: Metal', 'Stones: Faux Pearls'],
  },
  {
    id: '68',
    title: 'Western Leggings',
    adminId: getAdminId(67),
    description: 'Stretchable and comfortable leggings for everyday wear.',
    price: 22.00,
    discount: 0,
    size: 'S, M, L, XL',
    colors: 'Black, Gray, Navy',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western leggings black'],
    specifications: ['Fabric: Cotton Lycra', 'Waist: High-rise'],
  },
  {
    id: '69',
    title: 'Men\'s Kurta with Jacket',
    adminId: getAdminId(68),
    description: 'A stylish kurta set that comes with a contrasting jacket.',
    price: 135.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Blue, White, Black',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens kurta with jacket blue'],
    specifications: ['Fabric: Silk Blend', 'Includes: Kurta, Pajama, Jacket'],
  },
  {
    id: '70',
    title: 'Women\'s Jumpsuit Saree',
    adminId: getAdminId(69),
    description: 'A modern and innovative jumpsuit saree for the fashion-forward woman.',
    price: 160.00,
    discount: 0,
    size: 'S, M',
    colors: 'Red, Black, Blue',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens jumpsuit saree red'],
    specifications: ['Fabric: Georgette', 'Style: Pre-draped'],
  },
  {
    id: '71',
    title: 'Kids\' Cartoon-Print Shirt',
    adminId: getAdminId(70),
    description: 'A fun shirt with cartoon prints that kids will love.',
    price: 28.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'White, Blue, Yellow',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids cartoon shirt white'],
    specifications: ['Fabric: Cotton', 'Sleeves: Full'],
  },
  {
    id: '72',
    title: 'Ethnic Hand-Painted Dupatta',
    adminId: getAdminId(71),
    description: 'A unique hand-painted dupatta that is a piece of art.',
    price: 75.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Multicolor',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic hand-painted dupatta'],
    specifications: ['Fabric: Chanderi Silk', 'Art: Madhubani Painting'],
  },
  {
    id: '73',
    title: 'Western Pleated Skirt',
    adminId: getAdminId(72),
    description: 'A classic pleated skirt for a timeless look.',
    price: 52.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Black, Pink, White',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western pleated skirt black'],
    specifications: ['Fabric: Polyester', 'Style: Accordion Pleats'],
  },
  {
    id: '74',
    title: 'Men\'s Traditional Turban',
    adminId: getAdminId(73),
    description: 'A majestic turban for a royal groom look.',
    price: 85.00,
    discount: 0,
    size: 'Standard',
    colors: 'Red, Gold, Pink',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens traditional turban red'],
    specifications: ['Fabric: Art Silk', 'Style: Jodhpuri Safa'],
  },
  {
    id: '75',
    title: 'Women\'s Long Skirt',
    adminId: getAdminId(74),
    description: 'A flowy long skirt with ethnic prints.',
    price: 68.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Blue, Red, Green',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens long skirt blue'],
    specifications: ['Fabric: Rayon', 'Length: Maxi'],
  },
  {
    id: '76',
    title: 'Kids\' Onesie',
    adminId: getAdminId(75),
    description: 'A cute and comfortable onesie for infants.',
    price: 32.00,
    discount: 0,
    size: 'S, M',
    colors: 'White, Blue, Pink',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids onesie white'],
    specifications: ['Fabric: Cotton Interlock', 'Closure: Snap Button'],
  },
  {
    id: '77',
    title: 'Ethnic Necklace Set',
    adminId: getAdminId(76),
    description: 'A complete necklace set with matching earrings.',
    price: 90.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Pearl',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic necklace set gold'],
    specifications: ['Material: Alloy', 'Stones: Kundan and Pearls'],
  },
  {
    id: '78',
    title: 'Western Blazer Dress',
    adminId: getAdminId(77),
    description: 'A chic blazer dress for a powerful and stylish statement.',
    price: 88.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Black, White, Pink',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western blazer dress black'],
    specifications: ['Fabric: Polyester', 'Style: Double-breasted'],
  },
  {
    id: '79',
    title: 'Men\'s Chikankari Kurta',
    adminId: getAdminId(78),
    description: 'An elegant kurta with fine Chikankari embroidery from Lucknow.',
    price: 145.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'White, Light Blue',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens chikankari kurta white'],
    specifications: ['Fabric: Cotton', 'Embroidery: Chikankari'],
  },
  {
    id: '80',
    title: 'Women\'s Cape Top',
    adminId: getAdminId(79),
    description: 'A stylish top with an attached cape for a dramatic flair.',
    price: 58.00,
    discount: 0,
    size: 'S, M',
    colors: 'Black, White, Maroon',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens cape top black'],
    specifications: ['Fabric: Georgette', 'Style: Layered'],
  },
  {
    id: '81',
    title: 'Kids\' Romper Suit',
    adminId: getAdminId(80),
    description: 'An adorable romper suit for babies, easy to wear.',
    price: 35.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Pink, White',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids romper suit blue'],
    specifications: ['Fabric: Cotton', 'Closure: Snap Buttons'],
  },
  {
    id: '82',
    title: 'Ethnic Hair Accessories',
    adminId: getAdminId(81),
    description: 'A set of traditional hair accessories for braids and buns.',
    price: 28.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Gold, Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic hair accessories gold'],
    specifications: ['Includes: Juda Pin, Hair Chain', 'Material: Metal'],
  },
  {
    id: '83',
    title: 'Western Boyfriend Jeans',
    adminId: getAdminId(82),
    description: 'Relaxed fit boyfriend jeans for ultimate comfort and style.',
    price: 62.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Black',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western boyfriend jeans blue'],
    specifications: ['Fabric: Denim', 'Fit: Boyfriend'],
  },
  {
    id: '84',
    title: 'Men\'s Angrakha Kurta',
    adminId: getAdminId(83),
    description: 'A traditional Angrakha style kurta with a side-tie design.',
    price: 98.00,
    discount: 0,
    size: 'L, XL',
    colors: 'White, Black, Blue',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens angrakha kurta white'],
    specifications: ['Fabric: Cotton', 'Style: Angrakha'],
  },
  {
    id: '85',
    title: 'Women\'s Dhoti Saree',
    adminId: getAdminId(84),
    description: 'A pre-draped dhoti saree for a hassle-free, modern ethnic look.',
    price: 175.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Red, Blue, Black',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens dhoti saree red'],
    specifications: ['Fabric: Lycra', 'Style: Pre-stitched'],
  },
  {
    id: '86',
    title: 'Kids\' Denim Skirt',
    adminId: getAdminId(85),
    description: 'A cute and versatile denim skirt for little girls.',
    price: 38.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Black',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids denim skirt blue'],
    specifications: ['Fabric: Denim', 'Style: A-line'],
  },
  {
    id: '87',
    title: 'Ethnic Bindi Pack',
    adminId: getAdminId(86),
    description: 'A pack of decorative bindis in various shapes and colors.',
    price: 10.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Multicolor',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic bindi pack multicolor'],
    specifications: ['Type: Sticker Bindi', 'Quantity: 100+'],
  },
  {
    id: '88',
    title: 'Western Peplum Top',
    adminId: getAdminId(87),
    description: 'A top with a flared peplum waist for a flattering shape.',
    price: 48.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'White, Black, Pink',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western peplum top white'],
    specifications: ['Fabric: Cotton Blend', 'Fit: Fit and Flare'],
  },
  {
    id: '89',
    title: 'Men\'s Linen Shirt',
    adminId: getAdminId(88),
    description: 'A breathable linen shirt, perfect for summer days.',
    price: 55.00,
    discount: 0,
    size: 'M, L, XL, XXL',
    colors: 'White, Beige, Light Blue',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens linen shirt white'],
    specifications: ['Fabric: 100% Linen', 'Fit: Regular'],
  },
  {
    id: '90',
    title: 'Women\'s Asymmetric Kurta',
    adminId: getAdminId(89),
    description: 'A kurta with a modern, asymmetric hemline.',
    price: 62.00,
    discount: 0,
    size: 'M, L',
    colors: 'Black, White, Blue',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens asymmetric kurta black'],
    specifications: ['Fabric: Cotton', 'Hemline: High-Low'],
  },
  {
    id: '91',
    title: 'Kids\' Tutu Dress',
    adminId: getAdminId(90),
    description: 'A fluffy tutu dress for the little ballerina in your life.',
    price: 55.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Pink, White, Purple',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids tutu dress pink'],
    specifications: ['Fabric: Tulle', 'Style: Ballerina'],
  },
  {
    id: '92',
    title: 'Ethnic Bridal Veil (Dupatta)',
    adminId: getAdminId(91),
    description: 'A heavily embellished veil to complete a bridal lehenga.',
    price: 110.00,
    discount: 0,
    size: 'Free Size',
    colors: 'Red, Maroon',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic bridal veil red'],
    specifications: ['Fabric: Net', 'Work: Stone and Zari'],
  },
  {
    id: '93',
    title: 'Western Off-Shoulder Top',
    adminId: getAdminId(92),
    description: 'A trendy off-shoulder top for a chic look.',
    price: 40.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'White, Black, Red',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western off-shoulder top white'],
    specifications: ['Fabric: Cotton', 'Sleeves: Flared'],
  },
  {
    id: '94',
    title: 'Men\'s Khadi Jacket',
    adminId: getAdminId(93),
    description: 'A jacket made from handspun khadi fabric.',
    price: 85.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'Beige, Brown, Black',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens khadi jacket beige'],
    specifications: ['Fabric: Khadi Cotton', 'Pockets: 3'],
  },
  {
    id: '95',
    title: 'Women\'s Pant Saree',
    adminId: getAdminId(94),
    description: 'A modern fusion of pants and saree, easy to wear and stylish.',
    price: 155.00,
    discount: 0,
    size: 'S, M',
    colors: 'Black, Maroon, Navy',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens pant saree black'],
    specifications: ['Fabric: Georgette and Lycra', 'Style: Pre-stitched'],
  },
  {
    id: '96',
    title: 'Kids\' Capris',
    adminId: getAdminId(95),
    description: 'Comfortable capri pants for kids for everyday play.',
    price: 25.00,
    discount: 0,
    size: 'S, M, L',
    colors: 'Blue, Gray, Black',
    category: 'Kids',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['kids capris blue'],
    specifications: ['Fabric: Cotton Twill', 'Length: 3/4'],
  },
  {
    id: '97',
    title: 'Ethnic Toe Rings',
    adminId: getAdminId(96),
    description: 'A pair of adjustable silver-plated toe rings.',
    price: 15.00,
    discount: 0,
    size: 'Adjustable',
    colors: 'Silver',
    category: 'Ethnic',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['ethnic toe rings silver'],
    specifications: ['Material: German Silver', 'Adjustable design'],
  },
  {
    id: '98',
    title: 'Western Shirt Dress',
    adminId: getAdminId(97),
    description: 'A comfortable and stylish dress designed like a long shirt.',
    price: 68.00,
    discount: 0,
    size: 'M, L, XL',
    colors: 'White, Blue Stripe',
    category: 'Western',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['western shirt dress white'],
    specifications: ['Fabric: Cotton Poplin', 'Includes: Fabric Belt'],
  },
  {
    id: '99',
    title: 'Men\'s Printed T-shirt',
    adminId: getAdminId(98),
    description: 'A casual t-shirt with cool, modern prints.',
    price: 25.00,
    discount: 0,
    size: 'S, M, L, XL',
    colors: 'Black, White, Gray',
    category: 'Men',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['mens printed t-shirt black'],
    specifications: ['Fabric: 100% Cotton', 'Print: Graphic'],
  },
  {
    id: '100',
    title: 'Women\'s Cold-Shoulder Top',
    adminId: getAdminId(99),
    description: 'A top with cut-outs at the shoulders for a trendy look.',
    price: 42.00,
    discount: 50,
    size: 'S, M, L',
    colors: 'Black, White, Red',
    category: 'Women',
    imageUrls: ['https://placehold.co/600x800.png'],
    imageHints: ['womens cold-shoulder top black'],
    specifications: [
        'Fabric: Cotton Blend',
        'Fit: Regular',
        'Sleeve: Cold-Shoulder'
      ],
  },
];
